### PR TITLE
Update to Clojure 1.10.0 and tools.deps 0.6.480

### PR DESCRIPTION
**Pull request by cbowdon**
This brings in the tools.deps fix for Maven classifiers among other fixes.

### CODE REVIEW

**Comment by mikeananev** [comment]
Check our fork: [](https://github.com/mikeananev/cambada)

**Comment by mikeananev** [comment]
Check our fork: https://github.com/mikeananev/cambada

**Comment by cbowdon** [comment]
Nice, thanks @mikeananev

**Comment by luchiniatwork** [comment]
Closing this one as I have brought them in.

**Pull request closed without merging**
